FROM python:3.5

# Python requirements
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY requirements /usr/src/app
RUN pip3 install --no-cache-dir -r requirements

# Python code
COPY . /usr/src/app
